### ISSUE TITLE
It's outdated!

### ISSUE THREAD

**Issue by veyselerden** [flathub/org.onlyoffice.desktopeditors#12]
Current version is 5.5.1 while on Flathub it's 5.4.1. Needs rebuilding I guess.

**Comment by alexpattyn** [comment]
See the existing issue: https://github.com/flathub/org.onlyoffice.desktopeditors/issues/8
Which was addressed by: https://github.com/flathub/org.onlyoffice.desktopeditors/pull/11

This should taken care of now and this issue can be closed.
