### ISSUE TITLE
Files can not be opened with file managers.

### ISSUE THREAD

**Issue by queeup** [flathub/org.onlyoffice.desktopeditors#13]
I am using Elementary OS and file manager of my os is refused to open doc files with onlyoffice.

**Workaround**: Change Exec key on the org.onlyoffice.desktopeditors.desktop file
`~/.local/share/flatpak/app/org.onlyoffice.desktopeditors/current/active/export/share/applications/org.onlyoffice.desktopeditors.desktop`
```diff
--- Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=desktopeditors org.onlyoffice.desktopeditors
+++ Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=desktopeditors --file-forwarding org.onlyoffice.desktopeditors @@ %F @@
```

Unfortunately I can't figure it out opening files with space on the name of file. File names without space are working as expected with above workaround.

```shell
$ flatpak --version 
Flatpak 1.6.3

$ flatpak list 
Name                                 Application ID                                 Sürüm                     Branch           Installation
ONLYOFFICE Desktop Editors           org.onlyoffice.desktopeditors                  5.5.1                     stable           user

$ head -2 /etc/os-release
NAME="elementary OS"
VERSION="5.1.4 Hera"
```

**Comment by queeup** [comment]
OK. Found the open problem about named with some space character files.

`~/.local/share/flatpak/app/org.onlyoffice.desktopeditors/current/active/files/bin/desktopeditors`
```diff
--- exec ./DesktopEditors $@
+++ exec ./DesktopEditors "$@"
```

**Comment by mkazlouski** [comment]
Experiencing the same behavior on Fedora 30.
