### ISSUE TITLE
Missing CJK fonts

### ISSUE THREAD

**Issue by kogiokka** [flathub/org.onlyoffice.desktopeditors#17]
OnlyOffice display CJK characters with white squares.

![white_squares_onlyoffice](https://user-images.githubusercontent.com/36656205/84782789-07d18a80-b01b-11ea-906d-c6110a64b273.png)

Might relate to #2

**Comment by discretetimes** [comment]
According to onlyoffice issue "Not loading systems fonts on v5.4.2 ", I copy my /usr/share/fonts folder to $HOME/.fonts, now onlyoffice can display CJK characters.
# https://github.com/ONLYOFFICE/DesktopEditors/issues/294

**Comment by discretetimes** [comment]
> According to onlyoffice issue "Not loading systems fonts on v5.4.2 ", I copy my /usr/share/fonts folder to $HOME/.fonts, now onlyoffice can display CJK characters.
> # [ONLYOFFICE/DesktopEditors#294](https://github.com/ONLYOFFICE/DesktopEditors/issues/294)

Update:
Now on fedora, the problem no longer exists.
Fedora 34
Flatpak 1.10.2
ONLYOFFICE Desktop Editors                            org.onlyoffice.desktopeditors                    6.2.0                    stable            system

**Comment by ShockwaveNN** [comment]
I'm closing this issue since I think we've released a fix of this problem. If not - feel free to report new issue or comment here
