### ISSUE TITLE
Desktop editors can only access directories mapped on XDG dirs.

### ISSUE THREAD

**Issue by pemmoura** [flathub/org.onlyoffice.desktopeditors#18]
Due to the configuration of the flatpak in org.onlyoffice.desktopeditors.json:

```
    "finish-args": [
        ...
        "--filesystem=xdg-pictures",
        "--filesystem=xdg-desktop",
        "--filesystem=xdg-videos",
        "--filesystem=xdg-documents",
        "--filesystem=xdg-download",
        ...
]
```

This can be fixed by changing it to :

```
--filesystem=host
--filesystem=xdg-config/kdeglobals:ro
```

**Comment by tommytran732** [comment]
I really do not think this idea. There is no reason why it needs full access to the host directory. Having access to xdg-documents, xdg-pictures, xdg-documents and xdg-download is way more enough. Having --filesystem=host essentially makes the sandbox meaningless, especially when the app really got no reason to get full host file system access. 

I think using portals would be a better solution.

**Comment by janxkoci** [comment]
I have my documents in Dropbox, other people mentioned Nextcloud etc. So having more directories to show up can be helpful, I guess.

But I never really cared - I open my files either from my file manager or using the "Recent files" list of OO.

**Comment by ShockwaveNN** [comment]
I think we implemented opening not only XDG dir - I'll close this issue. Feel free to comment or report new issue if got any troubles
