### ISSUE TITLE
Show OnlyOffice Flatpak Version in "Open With" application list (Nautilus) 

### ISSUE THREAD

**Issue by eganonoa** [flathub/org.onlyoffice.desktopeditors#19]
Hello,

I am using the latest flatpak version on OnlyOffice in Debian 10 Buster (Gnome). OnlyOffice is not presented in the list of applications when right-click to "open with" a file in Nautilus/Gnome Files. This does not happen in the .deb or snap versions.

To fix you need to add %f at the end of the Exec line in /var/lib/flatpak/exports/share/applications/org.onlyoffice.desktopeditors.desktop

After that everything works as expected.

Thanks

**Comment by janxkoci** [comment]
This works just fine in elementary OS 5 with Pantheon Files. I can right-click files and select to open them in OnlyOffice without issues. I have OO 6.2, but it was also working in the past, since I can remember.

**Comment by ShockwaveNN** [comment]
Closing this issue since I think we've released fix for this problem.
If not - please create a new issue, I think it'll be better
