### ISSUE TITLE
Doesn't show fonts installed in /usr/share/fonts

### ISSUE THREAD

**Issue by MischievousTomato** [flathub/org.onlyoffice.desktopeditors#26]
As title says, the program doesn't show the fonts inside that directory.
I can only get more fonts to show if i copy them to .local/share/fonts

**Comment by wiad** [comment]
Same here, fonts from `usr/share/fonts` are not showing. Copying fonts to `$HOME/.local/share/fonts` works but that should not be necessary.

**Comment by romandemidov** [comment]
Fixed by https://github.com/ONLYOFFICE/core/pull/469/files

**Comment by ShockwaveNN** [comment]
Closing this issue since it should be fixed
If not - please comment here and I'll reopen it
