### ISSUE TITLE
Drag and drop Support

### ISSUE THREAD

**Issue by fahad-irshad** [flathub/org.onlyoffice.desktopeditors#38]
Is there any plans at all for drag and drop support? and adding multiple images at once. It seems idiotic to build a pretty app like this without basic features.

**Comment by janxkoci** [comment]
Already reported upstream (https://github.com/ONLYOFFICE/DesktopEditors/issues/616) and not relevant for flathub, since it also doesn't work in other packaging formats (I just checked with appimage from their website).

Consider closing this issue.

**Comment by ShockwaveNN** [comment]
Closing this issue, since it's reported it our main repo and not related to flatpak
