### ISSUE TITLE
OnlyOffice doesn't start after update to 6.3.1

### ISSUE THREAD

**Issue by janxkoci** [flathub/org.onlyoffice.desktopeditors#41]
Today I updated OnlyOffice to 6.3.1 and now the office does not start with any GUI method:

- clicking icon in the dock, launcher, or using synapse launcher
- right-clicking a file in Pantheon Files

The only method that works for launching it is the terminal, which shows these warnings:

```bash
$ flatpak run org.onlyoffice.desktopeditors
Gtk-Message: 11:08:32.654: Failed to load module "pantheon-filechooser-module"
Gtk-Message: 11:08:32.728: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:08:32.729: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
QApplication: invalid style override passed, ignoring it.
```

**System**

- elementary OS Hera 5.1.7 (based on Ubuntu 18.04)
- flatpak version 1.8.3

**Comment by italopinto** [comment]
Today I've got exactly the same problem after I updated to OnlyOffice 6.3.1 and I also tried to launch it in the terminal. Got the same output. So I will give my system information.

### System
+ POP_OS! 20.04 (based on Ubuntu 20.04)
+ Flatpak version 1.8.5

**Comment by AlienTux** [comment]
Same issue here. Same solution.

**System**

- Solus 4.3 Fortitude (Gnome Edition)
- Flatpak version 1.10.2

**Comment by XDmitryK** [comment]
Thanks for the feedback.
I can confirm - this is bug, issue 51316 in our private issue tracker.

**Comment by janxkoci** [comment]
Just got an update and the issue is fixed. Closing.

**Comment by t3kg33k** [comment]
Same here

**Comment by ShockwaveNN** [comment]
Thank all of you for this bug report!
