### ISSUE TITLE
Issue Opening Files on SMB Linux

### ISSUE THREAD

**Issue by andiskufi** [flathub/org.onlyoffice.desktopeditors#59]
Hi,

I try to open files from an smb share but it will not open the file, only a blank file appears.
ONLYOFFICE Desktop Editors version 7.0.1.37.

Thanks

**Comment by ShockwaveNN** [comment]
Hi, could you describe your host os and how SMB share is mounted?

I've got SMB share mounted via fstab on Kubuntu 20.04 and I successfully opened doc file from this share:

**Comment by andiskufi** [comment]
Hi, It's a smb connection to my work file server which I connect through dolphin in kde.
So a simple connection like mine it's not seen by the program. Is it possible to be fixed?
Otherwise can you direct me on how to mount the smb share with fstab?

**Comment by ShockwaveNN** [comment]
There is a lot of guides on how to mount smb via fstab, you can read some info [here](https://askubuntu.com/a/157140/39452)

> to my work file server which I connect through dolphin in KDE.

If you describe (report a video possible) how you do that I think I can analyze it
But if you using smb share via Dolphin only, without mounting it - I don't think we can call Dolphin in "Open Dialog"

**Comment by ShockwaveNN** [comment]
Also, any other flatpak applications on your system could access this share?

**Comment by andiskufi** [comment]
You are correct I can't see that smb location with any flatpak. Sorry if this is a general security feature of flatpak.
So I will have to mount it then. How I can do that if you could point me to the right direction?

**Comment by ShockwaveNN** [comment]
In that case I'll close this issue, feel free to comment if got any more ideas
