### ISSUE TITLE
OnlyOffice only show only few selected folders in Open Document dialog

### ISSUE THREAD

**Issue by bengtfredh** [flathub/org.onlyoffice.desktopeditors#6]
OnlyOffice flatpak is restricted to the open documents from folders pictures, desktop, videos, documents and download. This need to be documented or changed. For me this make OnlyOffice not so useable. I like to organize my documents outside documents folder like in synced folder for nextcloud or seafile. It is easily fixed by edit
```
/var/lib/flatpak/app/org.onlyoffice.desktopeditors/x86_64/stable/active/metadata
```
Change the the line
```
filesystems=xdg-download;xdg-documents;xdg-videos;xdg-pictures;xdg-desktop;
```
to
```
filesystems=home;
```
I understand the recommendation about restricting access to folder as much as possible for flatpaks. But this this kind of application i think the maker more sense to give access to home.

**Comment by janxkoci** [comment]
Note that `flatpak` has [commands](https://docs.flatpak.org/en/latest/sandbox-permissions.html) to manage permissions like this, no need to edit configuration files. And there is even a GUI app to handle this - [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal), so you don't even need a terminal.

**Comment by ShockwaveNN** [comment]
I think this issue resolved as well as https://github.com/flathub/org.onlyoffice.desktopeditors/issues/18
