### ISSUE TITLE
Translated params causes inconsistent behavior pt-br version of VLOOKUP

### ISSUE THREAD

**Issue by daudtivan** [flathub/org.onlyoffice.desktopeditors#72]
While working in a spreadsheet with VLOOKUP I noticed using the word "FALSO" (the translated version of FALSE in pt-br) as last parameter of the function does not return an exact match, but an approximate one.

Took me some time troubleshooting it, till I simply typed FALSE as parameter and voilà! That solved the issue.

Worth checking how translations are handled in this function/the app.
BTW, the function is named PROCV() in pt-br.

System Info:
ONLYOFFICE Desktop Editors versão 7.1.0.215 as flatpak
elementary OS 6.1 Jólnir (Ubuntu 20.04.3 LTS)
kernel Linux 5.15.0-43-generic

**Comment by ShockwaveNN** [comment]
Hi, could you make a same issue at https://github.com/ONLYOFFICE/DesktopEditors/ repo?

I cannot move it there but seems your issue is not related to flatpak, but can be reproduced in deb/rpm installation

**Comment by daudtivan** [comment]
Hi. Will do. No problem.
Tks
