### ISSUE TITLE
Update manifest 

### ISSUE THREAD

**Issue by alexpattyn** [flathub/org.onlyoffice.desktopeditors#8]
Seems that this package is behind the snap, deb, rpm, etc based on https://www.onlyoffice.com/download-desktop.aspx. 

I am assuming just the below needs to be updated?:

```
"type": "archive",
                    "url": "https://github.com/ONLYOFFICE/DesktopEditors/releases/download/ONLYOFFICE-DesktopEditors-5.4.2/onlyoffice-desktopeditors-x64.tar.gz",
                    "sha256": "41a36c030746e05a4556af930b15419ac94aaf7ba3f0b95ec99aa0f339dd050f",
                    "strip-components": 0

```

**Comment by bilelmoussaoui** [comment]
Yes, mind sending a merge request?

**Comment by alexpattyn** [comment]
https://github.com/flathub/org.onlyoffice.desktopeditors/pull/9

**Comment by alexpattyn** [comment]
https://github.com/flathub/org.onlyoffice.desktopeditors/pull/11 fixed this.
