### ISSUE TITLE
Why no version 7.2 yet?

### ISSUE THREAD

**Issue by ashrafrr** [flathub/org.onlyoffice.desktopeditors#83]
Why flatpak version for 7.2 is not released yet?
Any update or timeline please.

**Comment by ShockwaveNN** [comment]
Hi, we always release flatpak version a little bit after our major release, and now we skipped v7.2.0 and will release v7.2.1 soon

I've added a note to README about our release process

https://github.com/flathub/org.onlyoffice.desktopeditors/pull/84

**Comment by repoash** [comment]
Thanks for the clarification. When can we expect to get v7.2.1?

**Comment by ShockwaveNN** [comment]
Sorry, I cannot provide exact time frame, since we got several important task before it
